{% set build_version = "2.0.5" %}

package:
  name: jpeg-turbo
  version: {{ build_version }}

source:
  git_url: https://github.com/libjpeg-turbo/libjpeg-turbo
  git_rev: {{ build_version }}

build:
  number: 3

requirements:
  build: 
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}
    - autoconf
    - automake
    - libtool
    - cmake {{ cmake }}
    - make
    - nasm {{ nasm }} # [x86_64]
  host:
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}

test:
  requires:
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}
    - libstdcxx-ng  {{ libstdcxx }}

about:
  home: http://www.libjpeg-turbo.org/
  license: IJG, modified 3-clause BSD and zlib
  license_file: LICENSE.md
  summary: IJG JPEG compliant runtime library with SIMD and other optimizations

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
